package de.dkt.eservices.esesame;


public class TestConstants {
	
	public static final String pathToPackage = "rdftest/esesame-test-package.xml";
	
	public static final String inputData = "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
+"@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\n"
+"@prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .\n"
+"@prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .\n"
+"@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=494,505>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"5 September\"^^xsd:string ;\n"
+"        nif:beginIndex     \"494\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"505\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=00010905000000_00010906000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=399,403>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"July\"^^xsd:string ;\n"
+"        nif:beginIndex     \"399\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"403\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=00010701000000_00010702000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=407,416>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"September\"^^xsd:string ;\n"
+"        nif:beginIndex     \"407\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"416\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=00010901000000_00010902000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=0,813>\n"
+"        a                  nif:RFC5147String , nif:String , nif:Context ;\n"
+"        nif:beginIndex     \"0\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"813\"^^xsd:nonNegativeInteger ;\n"
+"        nif:isString       \"\"\"1936\n\nCoup leader Sanjurjo was killed in a plane crash on 20 July, leaving an effective command split between Mola in the North and Franco in the South. On 21 July, the fifth day of the rebellion, the Nationalists captured the main Spanish naval base at Ferrol in northwestern Spain. A rebel force under Colonel Beorlegui Canet, sent by General Emilio Mola, undertook the Campaign of Guipúzcoa from July to September. The capture of Guipúzcoa isolated the Republican provinces in the north. On 5 September, after heavy fighting the force took Irún, closing the French border to the Republicans. On 13 September, the Basques surrendered San Sebastián to the Nationalists, who then advanced toward their capital, Bilbao. The Republican militias on the border of Viscaya halted these forces at the end of September.\n\"\"\"^^xsd:string ;\n"
+"        nif:meanDateRange  \"02110711030000_16631213030000\"^^xsd:string .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=795,811>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"end of September\"^^xsd:string ;\n"
+"        nif:beginIndex     \"795\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"811\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=00010920000000_00010930000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=0,4>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"1936\"^^xsd:string ;\n"
+"        nif:beginIndex     \"0\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"4\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=19360101000000_19370101000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=156,163>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"21 July\"^^xsd:string ;\n"
+"        nif:beginIndex     \"156\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"163\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=19360721000000_19360722000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=598,610>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"13 September\"^^xsd:string ;\n"
+"        nif:beginIndex     \"598\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"610\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=00010913000000_00010914000000> .\n"
+"\n"
+"<http://dkt.dfki.de/examples/#char=58,65>\n"
+"        a                  nif:RFC5147String , nif:String ;\n"
+"        nif:anchorOf       \"20 July\"^^xsd:string ;\n"
+"        nif:beginIndex     \"58\"^^xsd:nonNegativeInteger ;\n"
+"        nif:endIndex       \"65\"^^xsd:nonNegativeInteger ;\n"
+"        nif:entity         <http://dkt.dfki.de/ontologies/nif#date> ;\n"
+"        itsrdf:taIdentRef  <http://dkt.dfki.de/ontologies/nif#date=19360720000000_19360721000000> .";

	public static final String inputDataRDF = 
"			<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n"
+"	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
+"	         xmlns:ns0=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#\"\n"
+"	         xmlns:ns1=\"http://www.w3.org/2005/11/its/rdf#\"\n"
+"	         xmlns:ns2=\"http://www.w3.org/2003/01/geo/wgs84_pos/\"\n"
+"	         xmlns:ns3=\"http://dkt.dfki.de/ontologies/nif#\">\n"

+"	  <rdf:Description rdf:about=\"http://dkt.dfki.de/documents/#char=41,45\">\n"
+"	    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"	    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"	    <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Marc</ns0:anchorOf>\n"
+"	    <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">41</ns0:beginIndex>\n"
+"	    <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">45</ns0:endIndex>\n"
+"	    <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"	    <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"	    <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11857745X\"/>\n"
+"  </rdf:Description>\n"


+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=2330,2343\">"
+" <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>"
+"  <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">San Francisco</ns0:anchorOf>"
+" <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2330</ns0:beginIndex>"
+"  <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2343</ns0:endIndex>"
+"  <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>"
+"  <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>"
+"  <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.77493</ns2:lat>"
+"  <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.41942</ns2:long>"
+"  <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5391959\"/>"
+"</ns0:RFC5147String>"

+"</rdf:RDF>";
	
	public static final String inputDataRDF2 = ""
+ "<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n"
+"<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
+"        xmlns:ns0=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#\"\n"
+"        xmlns:ns1=\"http://www.w3.org/2005/11/its/rdf#\"\n"
+"        xmlns:ns2=\"http://www.w3.org/2003/01/geo/wgs84_pos/\"\n"
+"        xmlns:ns3=\"http://dkt.dfki.de/ontologies/nif#\">\n"
+"\n"
+" <rdf:Description rdf:about=\"http://dkt.dfki.de/documents/#char=41,45\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Marc</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">41</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">45</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11857745X\"/>\n"
+" </rdf:Description>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2213,2223\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">California</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2213</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2223</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">47.27089</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-82.0929</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5932921\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=1064,1068\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eric</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1064</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1068</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11858071X\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=2330,2343\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">San Francisco</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2330</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2343</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.77493</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.41942</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5391959\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=3465,3472\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Orleans</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3465</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3472</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">47.90289</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">1.90389</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/2989317\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=4421,4427\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Europe</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4421</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4427</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">48.69096</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">9.14062</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/6255148\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2900,2904\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eric</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2900</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2904</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11858071X\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=345,358\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">San Francisco</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">345</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">358</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.77493</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.41942</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5391959\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=1487,1492\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">China</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1487</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1492</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">35</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">105</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/1814991\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2744,2751\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">England</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2744</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2751</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">52.16045</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-0.70312</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/6269131\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2060,2074\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Marine Country</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2060</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2074</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5370468/marin-county.html\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2772,2777\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Serge</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2772</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2777</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/131456016\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=2424,2429\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">China</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2424</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2429</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">35</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">105</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/1814991\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=1983,1998\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Treasure Island</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1983</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1998</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.82465</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.37108</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5403321\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=3117,3122\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Serge</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3117</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3122</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/131456016\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2820,2824\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eric</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2820</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2824</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11858071X\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2440,2446\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Russia</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2440</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2446</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">60</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">100</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/2017370\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2013,2020\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Oakland</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2013</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2020</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.80437</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.2708</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5378538\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=202,206\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eric</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">202</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">206</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11858071X\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2509,2517\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">New-York</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2509</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2517</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">40.71427</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-74.00597</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5128581\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=3403,3414\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Boulder Dam</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3403</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3414</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5298509/hoover-dam.html\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=2002,2010\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berkeley</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2002</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2010</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.87159</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.27275</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5327684\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=19,25\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">August</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">19</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">25</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#date\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://dkt.dfki.de/ontologies/nif#date=20160801000000_20160901000000\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=3561,3569\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">New-York</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3561</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3569</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">40.71427</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-74.00597</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5128581\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=1577,1590\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">San Francisco</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1577</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">1590</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.77493</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.41942</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5391959\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=4567,4575\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">1.9.1941</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4567</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4575</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#date\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://dkt.dfki.de/ontologies/nif#date=19410901000000_19410902000000\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:Context rdf:about=\"http://dkt.dfki.de/documents/#char=0,4577\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns3:averageLatitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">41.4370161111111</ns3:averageLatitude>\n"
+"   <ns3:averageLongitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-54.61663555555557</ns3:averageLongitude>\n"
+"   <ns3:standardDeviationLatitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">6.757305969218419</ns3:standardDeviationLatitude>\n"
+"   <ns3:standardDeviationLongitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">83.21405739925892</ns3:standardDeviationLongitude>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">0</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4577</ns0:endIndex>\n"
+"   <ns0:isString rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\"> 01 San Francisco, August 20th 41. Hotel Marc Hopkins. My Sweetheart - I am just stealing a moment&amp;apos;s pause to send my love to you. We have incredible Arctic days here in this breath taking town! - Eric is torn here to pieces and people are so hospitable that one does not knew where to go first. - Anyhow I wanted to tell you how beautiful San Francisco is. It is just the situation which is so unique and with nothing to be com= pared. The uniqueness of the town is that the Pacific is only connected with it by a small entrance - quite hidden by mountains - called the Golden Gate. Behind this Gate - this small entrance - the Pacific makes or better forms an endless Bay with many children Bays - surrounded by mountains - and the town itself is lying on a sort of Penin= sula stretched out into the huge Bay. This is of course the perfect harbour and as I said before the uniqueness of the place. The town is very mountaineous and as a whole a horror as all the American towns. The streets climb up, just straight up - the mountains and are so steep that Eric says: the cars need less a motor than brakes. It&amp;apos;s really quite frigthtening and the Francisco people enjoy to take the foreigners up and down this steep streets. It is an old fashioned town with Victorian [?] buildings - some indifferent skyscrapers - with no green left - with old fashioned tram= ways - also climbing up the steep straight streets - with its Chinatown, the biggest Chinese settle= ment outside China. People are a bit like French people. Very gay - light living. And until now I find San Francisco the town which is most interest in new architecture ideas. They feel here the responsibility which the lovely situa= tion imposes on them. You can&amp;apos;t imagine how many Luncheons - dinners - parties we had and we are having - the flowers - the chocolates and so on I have received- We have been take to all 02 [ ] 03 2 directions of the town - we have crossed the endless Bay Bridge - over Treasure Island to Berkeley - Oakland - and the lovely Golden Gate Bridge to Marine Country [sic] - We have been driven along the South Pacific coast to orchards - flower gardens - - we have been overwhelmed by the riches of this California! - Everybody wants us to stay here and I have the strong feeling that we will come back. 1 I believe that San Francisco and Los Angeles will have a great future in later times - open to the Pacific - China - India - Russia! - But for the time being it is the right thing to go back to New-York. Anyhow we have made many valuable contacts here in the West and Väti is very very appreciated here. He had last night a very impressive lecture for the society of the young, very serious architects. Much more serious than in England. - Of course we met Serge and Barbara. 2 They made their home here. Eric did not want to see him - but I convinced him, that to be large suits him (Eric) much better than to be narrow. They seem to have a difficult time - and Barbara is just lovely and the same. The oldest boy is like her - very handsome and he has a sweet expression. The little one is more like Serge and very Jewish looking. Everybody loves her - but not him. I can&amp;apos;t go into details about everything we have seen and done here - but we wore having a most interesting - stimulating time here. We are leaving on Friday the 22nd - south eastwards. First we are stopping at the Boulder Dam then [sic] at the Grand Canyon - then in San New- Orleans on the American Gulf - then up north= wards to the Tennessee Valley and to Washington - New-York. We shall be in N.Y. about the 1rst 04 [ ] 05 3 of September. We shall have one room at the Alden and don&amp;apos;t know yet how this will work and how everything will de= velop. Eric has to prepare his exhibition Christmas [?] - and to write articles about his im= pressions. Well - I am confident and and as you know, my dear, a believer. - I very often - in the middle of a conversation or in the middle of noisy cocktail parties - fly with my thoughts to you and I bless you my dear. All my love to you - All my sincerest wishes for you and mother and Lilli - and of course Hanne - everybody who asks for us - Yours ever Mutz P.I. I collected lovely shells and have made a charming necklace for you - but I could not send it - too many difficulties. I keep it for you. [Zeichnung einer Brücke über die Kontinente von E. Mendelsohn mit Beschriftung:] Europe Asia Minor America Suspension bridge in [?]ves - a mathematical problem to be solved! Benedictus 06 [ mit Notiz von fremder Hand:] Revised 1.9.1941. </ns0:isString>\n"
+"   <ns0:language rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">en</ns0:language>\n"
+"   <ns0:meanDateRange rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">19560425160000_20270107160000</ns0:meanDateRange>\n"
+" </ns0:Context>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=3621,3630\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">September</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3621</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3630</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#date\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://dkt.dfki.de/ontologies/nif#date=20160901000000_20161001000000\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=2348,2359\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Los Angeles</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2348</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">2359</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">34.05223</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-118.24368</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5368361\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=4,17\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">San Francisco</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">17</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">37.77493</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-122.41942</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/5391959\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=3548,3558\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Washington</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3548</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3558</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"file:///C:/Users/pebo01/workspace/e-openNLP/4064682-8\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:String rdf:about=\"http://dkt.dfki.de/documents/#char=3746,3750\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eric</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3746</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">3750</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#PER\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://d-nb.info/gnd/11858071X\"/>\n"
+" </ns0:String>\n"
+"\n"
+" <ns0:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=4439,4446\">\n"
+"   <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"   <ns0:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">America</ns0:anchorOf>\n"
+"   <ns0:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4439</ns0:beginIndex>\n"
+"   <ns0:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">4446</ns0:endIndex>\n"
+"   <ns0:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"   <ns0:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,4577\"/>\n"
+"   <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">39.76</ns2:lat>\n"
+"   <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-98.5</ns2:long>\n"
+"   <ns1:taIdentRef rdf:resource=\"http://www.geonames.org/6252001\"/>\n"
+" </ns0:RFC5147String>\n"
+"\n"
+"</rdf:RDF>			\n";
	
	public static final String inputDataRDF3 =""
+"<?xml version=\"1.0\" encoding=\"utf-8\" ?>\n"
+"<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
+"         xmlns:ns0= \"http://dkt.dfki.de/ontologies/nif#\"\n"
+"         xmlns:ns1=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#\"\n"
+"         xmlns:ns2=\"http://www.w3.org/2003/01/geo/wgs84_pos/\"\n"
+"         xmlns:ns3=\"http://www.w3.org/2005/11/its/rdf#\">\n"
+"	  <rdf:Description rdf:about=\"http://dkt.dfki.de/documents/#char=0,526\">\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#Context\"/>\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"    <ns0:averageLatitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">41.179235000000006</ns0:averageLatitude>\n"
+"    <ns0:averageLongitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-76.765435</ns0:averageLongitude>\n"
+"    <ns0:standardDeviationLatitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">6.757680839239522</ns0:standardDeviationLatitude>\n"
+"    <ns0:standardDeviationLongitude rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">54.25289633005988</ns0:standardDeviationLongitude>\n"
+"    <ns1:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">0</ns1:beginIndex>\n"
+"    <ns1:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">526</ns1:endIndex>\n"
+"    <ns1:isString rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\"> 01 [gedr. Briefkopf: Ojai Village Inn, Ojai, California] Friday 7th July. Beloved - I can&amp;apos;t get quite over the luxury of doing no= thing - knowing you at work. I have a very highly developped [sic] sense of conscienceness!! But being &quot;practical&quot; at the same time - and nothing can be done right now about it - I try to enjoy! - We had a comfortable trip to S.B. - getting warmer and warmer - though more looking at the heat outside than fee= ling it in the air condi= tioned parlour car. - 02 Inhalt 03 Inhalt 04 Inhalt </ns1:isString>\n"
+"    <ns1:language rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">en</ns1:language>\n"
+"  </rdf:Description>\n"
+"	  <ns1:String rdf:about=\"http://dkt.dfki.de/documents/#char=46,56\">\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#RFC5147String\"/>\n"
+"    <ns1:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">California</ns1:anchorOf>\n"
+"    <ns1:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">46</ns1:beginIndex>\n"
+"    <ns1:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">56</ns1:endIndex>\n"
+"    <ns1:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"    <ns1:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,526\"/>\n"
+"    <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">47.27089</ns2:lat>\n"
+"    <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-82.0929</ns2:long>\n"
+"    <ns3:taIdentRef rdf:resource=\"http://www.geonames.org/5932921\"/>\n"
+"  </ns1:String>\n"
+"	  <ns1:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=40,44\">\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"    <ns1:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Ojai</ns1:anchorOf>\n"
+"    <ns1:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">40</ns1:beginIndex>\n"
+"    <ns1:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">44</ns1:endIndex>\n"
+"    <ns1:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"    <ns1:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,526\"/>\n"
+"    <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">34.43722</ns2:lat>\n"
+"    <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-119.21567</ns2:long>\n"
+"    <ns3:taIdentRef rdf:resource=\"http://www.geonames.org/5378881\"/>\n"
+"  </ns1:RFC5147String>\n"
+"	  <ns1:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=35,38\">\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"    <ns1:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Inn</ns1:anchorOf>\n"
+"    <ns1:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">35</ns1:beginIndex>\n"
+"    <ns1:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">38</ns1:endIndex>\n"
+"    <ns1:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"    <ns1:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,526\"/>\n"
+"    <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">48.57161</ns2:lat>\n"
+"    <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">13.4625</ns2:long>\n"
+"    <ns3:taIdentRef rdf:resource=\"http://www.geonames.org/2775280\"/>\n"
+"  </ns1:RFC5147String>\n"
+"	  <ns1:RFC5147String rdf:about=\"http://dkt.dfki.de/documents/#char=22,26\">\n"
+"    <rdf:type rdf:resource=\"http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#String\"/>\n"
+"    <ns1:anchorOf rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Ojai</ns1:anchorOf>\n"
+"    <ns1:beginIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">22</ns1:beginIndex>\n"
+"    <ns1:endIndex rdf:datatype=\"http://www.w3.org/2001/XMLSchema#nonNegativeInteger\">26</ns1:endIndex>\n"
+"    <ns1:entity rdf:resource=\"http://dkt.dfki.de/ontologies/nif#LOC\"/>\n"
+"    <ns1:referenceContext rdf:resource=\"http://dkt.dfki.de/documents/#char=0,526\"/>\n"
+"    <ns2:lat rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">34.43722</ns2:lat>\n"
+"    <ns2:long rdf:datatype=\"http://www.w3.org/2001/XMLSchema#double\">-119.21567</ns2:long>\n"
+"    <ns3:taIdentRef rdf:resource=\"http://www.geonames.org/5378881\"/>\n"
+"  </ns1:RFC5147String>\n"
+"	</rdf:RDF>";

}
